; Filename: Exer5.asm
; Display
; Name: Joseph Xeno O. Banzon
; Date: August 28, 2025

.model small ; directive to use "small" memory model
.code ; section of programming containing executable code
.stack 100 ; define the size of the program's stack
start: ; start of the program

    mov ah,02h 
    mov cl,'a'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'b'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'c'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'d'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'e'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'f'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'g'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'h'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'i'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'j'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'k'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'l'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'m'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'n'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'o'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'p'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'q'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'r'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'s'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'t'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'u'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'v'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'w'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'x'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'y'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'z'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,0Ah
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'A'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'B'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'C'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'D'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'E'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'F'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'G'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'H'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'I'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'J'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'K'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'L'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'M'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'N'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'O'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'P'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'Q'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'R'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'S'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'T'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'U'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'V'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'W'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'X'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'Y'
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,' '
    mov dl,cl
    int 21h

    mov ah,02h 
    mov cl,'Z'
    mov dl,cl
    int 21h

    
int 27h
end start